server:
  port: 8880

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/bill-management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


# 整合Mybatis
mybatis:
  # ** 表示在mapper下不管有多少文件夹，都可以全部识别
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: billManagement.pojo
  #  打印sql相关的日志信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      # 要写上 eureka 的访问地址
      defaultZone: HTTP://127.0.0.1:10086/eureka